spring:
  datasource:
    url: jdbc:mysql://localhost:43306/hexagonal
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis: # Redis ?? ??
    host: redis
    port: 6379

logging.level:
  root: debug